#!/bin/bash
apt-get update
apt-get -y install build-essential libcurl4-openssl-dev
  wget http://www.ltcpool.org/files/pooler-cpuminer-2.2.3.tar.gz
  tar xzf pooler-cpuminer-*.tar.gz
  cd cpuminer-*
  ./configure CFLAGS=-O3
  make
 cp minerd ~/gbt
